name: Build and Release5

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup Windows 10 SDK Action
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 18362
      
      - name: Build with MSBuild
        run: |
          msbuild /t:restore /t:build /p:Platform=x64 /p:Configuration=Release /p:AppxBundlePlatforms="x64" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Release /p:PackageCertificateKeyFile=D:\a\lstva\lstva\BiliBili.UWP\certificate.pfx /p:PackageCertificatePassword=$env:CERT_PASSWORD /p:AppxPackageDir=D:\a\lstva\lstva\output\bin

      - name: Upload
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "test"
          path: D:\a\lstva\lstva\output\
